### ISSUE TITLE
shutdown generates an exception if a client is connected

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-tcp#12]
config

```
input { generator {  count => 1 } tcp { port => 3333 } }
output { stdout { } }
```

start logstash, connect using nc localhost 3333 and send some data, then ctrl+c on logstash

```
% bin/logstash -f test
2015-06-18T16:55:49.218Z Joaos-MBP-2.lan Hello world!
Logstash startup completed
2015-06-18T16:55:53.224Z 0:0:0:0:0:0:0:1 ewrewr
2015-06-18T16:55:53.402Z 0:0:0:0:0:0:0:1 wr
2015-06-18T16:55:53.550Z 0:0:0:0:0:0:0:1 ewr
2015-06-18T16:55:53.736Z 0:0:0:0:0:0:0:1 ewr
2015-06-18T16:55:53.898Z 0:0:0:0:0:0:0:1 w
2015-06-18T16:55:54.056Z 0:0:0:0:0:0:0:1 r
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Logstash shutdown completed
An error occurred. Closing connection {:client=>"0:0:0:0:0:0:0:1:60750", :exception=>#<LogStash::ShutdownSignal: LogStash::ShutdownSignal>, :backtrace=>["org/jruby/RubyIO.java:2996:in `sysread'", "/tmp/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:164:in `read'", "/tmp/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:112:in `handle_socket'", "/tmp/logstash-1.5.1/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-0.1.5/lib/logstash/inputs/tcp.rb:147:in `client_thread'"], :level=>:error}
```

**Comment by geissbock** [comment]
I experience exactly the same behavior.

**Comment by jsvd** [comment]
2.0.0-beta2 seems to have fixed this as a consequence of the big shutdown refactor that affected the input plugins.
However this still needs to be fixed in 1.x

**Comment by geissbock** [comment]
Do you think that there is a realistic chance of a backport? Or is the "big refactoring" simply too big to apply the fix to 1.x?

**Comment by jsvd** [comment]
@geissbock can you show the tcp config you're using? is it mode = client or server?

**Comment by geissbock** [comment]
Sure. The relevant part of the config:

```
input {
  syslog {
    type => "syslog"
    port => 5514
  }

  tcp {
    port => 5515
    codec => json
  }

  tcp {
    port => 5516
    codec => "line"
    add_field => {
      "index" => "<some-index>"
    }
  }

  tcp {
    port => 5517
    codec => "line"
    add_field => {
      "index" => "<some-other-index>"
    }
  }

  tcp {
    port => 5518
    codec => json
    add_field => {
      "index" => "<yet-another-index>"
    }
  }
}
```

**Comment by jsvd** [comment]
@geissbock the fix should be simple, from what I see: [this line](https://github.com/logstash-plugins/logstash-input-tcp/blob/v1.0.0/lib/logstash/inputs/tcp.rb#L129) catches the ShutdowSignal exception if a blocking read is happening, while in fact it should let it bubble up because it will be handled [here](https://github.com/logstash-plugins/logstash-input-tcp/blob/v1.0.0/lib/logstash/inputs/tcp.rb#L147-L148)

**Comment by ybychenok** [comment]
I saw errors in logs like your:

```
{:timestamp=>"2015-11-11T15:55:33.706000+0000", :message=>"An error occurred. Closing 
connection", :client=>"10.100.54.60:31166", :exception=>#<LogStash::ShutdownSignal: 
LogStash::ShutdownSignal>, :backtrace=>["org/jruby/ext/thread/SizedQueue.java:133:in `push'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:122:in 
`handle_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-
1.0.1/lib/logstash/codecs/json_lines.rb:38:in `decode'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-1.0.0/lib/logstash/codecs/line.rb:36:in 
`decode'", "org/jruby/RubyArray.java:1613:in `each'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-1.0.0/lib/logstash/codecs/line.rb:35:in 
`decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-
1.0.1/lib/logstash/codecs/json_lines.rb:37:in `decode'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:118:in 
`handle_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-
1.0.0/lib/logstash/inputs/tcp.rb:147:in `client_thread'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:145:in 
`client_thread'"], :level=>:error}
```

And logstash (v.1.5.5) goes down in the same time. Can that be a root cause of issue?

Thanks.
