### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-tcp#15]
```
Failures:

  1) LogStash::Inputs::Tcp should connection threads are cleaned up when connection is closed
     Failure/Error: Timeout.timeout(1) {sleep 0.1 while client_threads.size > 0}
     NoMethodError:
       undefined method `size' for nil:NilClass
     # ./spec/inputs/tcp_spec.rb:244:in `(root)'
     # ./spec/inputs/tcp_spec.rb:244:in `(root)'
     # ./spec/inputs/tcp_spec.rb:228:in `(root)'

Finished in 2.75 seconds (files took 5.03 seconds to load)
9 examples, 1 failure
```
http://build-eu-1.elasticsearch.org/view/LS%20Inputs/job/logstash_plugin_input_tcp/lastBuild/console

**Comment by purbon** [comment]
old issue, closing this for now
