### ISSUE TITLE
New incoming connections not `accept()`-ed 

### ISSUE THREAD

**Issue by jstangroome** [logstash-plugins/logstash-input-tcp#16]
I am running logstash 1.4.5 (-1-a2bacae) on Ubuntu 14.04.1 LTS, kernel 3.13.0-36-generic x86_64 and Java from  openjdk-7-jre-headless=7u75-2.5.4-1~trusty1.

I have the following TCP+TLS input configured:

```
tcp {
  port => 6514
  codec => line
  data_timeout => 120
  ssl_enable => true
  ssl_cert => "/etc/logstash/tls/ourcert.pem"
  ssl_key => "/etc/logstash/tls/ourkey.pem"
  type => "syslog-over-tls"
}
```

When logstash starts it begins accepting incoming connections from about 20 remote hosts, geographically distributed. Logstash also processes the incoming data on these connections and sends to our outputs (statsd, elasticsearch).

After a few minutes, new incoming connections arrive. The kernel performs the SYN/SYN+ACK/ACK handshake, puts these connections in the `ESTABLISHED` state and into logstash's listen backlog. Logstash continues processing data on the incoming connections and sending to our outputs but does not `accept` the new connections on the listen backlog. Over time the backlog grows.

Because the kernel has established the connection, the remote end thinks everything is good.

Running `watch 'ss -anpt sport = :6514'` shows this in action, here is a sample output with IP addresses removed:

```
State      Recv-Q Send-Q   :Port
LISTEN     4      50       :6514   users:(("java",1851,28))
ESTAB      0      0        :52301  users:(("java",1851,35))
ESTAB      0      0        :38714  users:(("java",1851,64))
ESTAB      0      0        :35478  users:(("java",1851,59))
ESTAB      305    0        :53403
ESTAB      305    0        :60525
ESTAB      0      0        :36547  users:(("java",1851,63))
ESTAB      305    0        :49315
ESTAB      0      0        :45487  users:(("java",1851,43))
ESTAB      0      0        :39752  users:(("java",1851,42))
ESTAB      0      0        :56869  users:(("java",1851,34))
ESTAB      0      0        :44424  users:(("java",1851,37))
ESTAB      0      0        :40604  users:(("java",1851,74))
ESTAB      0      0        :40573  users:(("java",1851,17))
ESTAB      0      0        :53410
ESTAB      0      0        :41848  users:(("java",1851,38))
```

The `ESTAB` connections without the owner process details (ie `users:((...)))`) are the un-`accept()`-ed connections. Most of these have a ~300 Recv-Q which I presume is the TLS client hello. The number of these `ESTAB` connections corresponds with the Recv-Q value of the `LISTEN` entry - `4` in this example.

Sending `SIGQUIT` to the logstash Java process to dump the all the thread call stacks shows the following for the tcp input thread:

```
"<tcp" daemon prio=10 tid=0x0000000000888800 nid=0x76a runnable [0x00007f0ff3efb000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000000e4e93a40> (a sun.nio.ch.Util$2)
        - locked <0x00000000e4e93a28> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000e60c8f38> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
        at org.jruby.ext.openssl.SSLSocket$2.run(SSLSocket.java:342)
        at org.jruby.RubyThread.executeBlockingTask(RubyThread.java:1065)
        at org.jruby.ext.openssl.SSLSocket.waitSelect(SSLSocket.java:319)
        at org.jruby.ext.openssl.SSLSocket.doHandshake(SSLSocket.java:437)
        at org.jruby.ext.openssl.SSLSocket.acceptCommon(SSLSocket.java:270)
        at org.jruby.ext.openssl.SSLSocket.accept(SSLSocket.java:232)
        at org.jruby.ext.openssl.SSLSocket$INVOKER$i$0$0$accept.call(SSLSocket$INVOKER$i$0$0$accept.gen)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
```

If you need more information, I'm happy to provide it. I'm keen to diagnose and fix this problem but I'm not sure where to look next.

**Comment by jstangroome** [comment]
I have reverted the logstash configuration to use a TCP input without SSL enabled and have instead placed an SSL-terminating proxy in front logstash. This has worked around the issue, and would suggest that the issue is related to `SSLSocket.accept()` as the rest of the TCP input code path is identical.

**Comment by jstangroome** [comment]
This same issue was experienced with the `logstash-input-lumberjack` plugin but I found that adopting a later build which uses `SSLSocket.accept_nonblock` resolved the problem. Perhaps this TCP input plugin could adopt a similar approach.

See https://github.com/logstash-plugins/logstash-input-lumberjack/issues/61#issuecomment-148885242

**Comment by purbon** [comment]
this looks interesting bug/situation, can you verify this with the last version and jdk8? what do you think?

**Comment by purbon** [comment]
@jstangroome I tried to reproduce this behaviour with the last released version ```2.1.0``` and can not make this happen, are you able to confirm that? thanks a lot for your report.

**Comment by jstangroome** [comment]
@purbon It is difficult to reproduce the issue outside of the Production environment. I hope to be able to deploy the latest Logstash to Production in the coming weeks and will advise if the issue still occurs.

**Comment by purbon** [comment]
@jstangroome thanks, much appreciate. I wonder if we can might be replicate your environment somehow, are you ok describing this a bit here?
