### ISSUE TITLE
null cert chain

### ISSUE THREAD

**Issue by pbmsys** [logstash-plugins/logstash-input-tcp#33]
After upgrading to 3.0.0 i see this error as well, along with the fact that the IOerror still persists.

{:timestamp=>"2015-12-17T08:26:12.641000+0100", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: null cert chain>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:206:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:199:in `start_input'"], :level=>:error}

any insight.

**Comment by ranman** [comment]
can you throw that comment above into a  triple \`\`\`  insert code here \`\`\`
block?

This could be related to you having ssl_verify = true on and your client not offering a cert

**Comment by pbmsys** [comment]
@ranman You are totally correct, took the wrong line in the log, sorry.
Changed the above :)

**Comment by pbmsys** [comment]
Any updates on this issue?

**Comment by hydrapolic** [comment]
Same problem. I fail to get version 3.0 working either with a self-signed certificate on the server side or with a normal certificate with a chain.

**Comment by hydrapolic** [comment]
If ssl_verify => true, the server will offer all SSL certificates in the chain AND it will verify the client certificate. Otherwise the server will NOT offer the SSL certificate chain certificates and does not client certificate checking.

Since I need the SSL certificate chain to be present when the SSL handshake starts AND I don't want to verify clients, how about:

# diff -u tcp.rb.virgin tcp.rb
--- tcp.rb.virgin       2016-01-05 16:34:27.866630631 +0000
+++ tcp.rb      2016-01-05 16:48:05.338448322 +0000
@@ -212,8 +212,8 @@
       @ssl_context = OpenSSL::SSL::SSLContext.new
       @ssl_context.cert = OpenSSL::X509::Certificate.new(File.read(@ssl_cert))
       @ssl_context.key = OpenSSL::PKey::RSA.new(File.read(@ssl_key),@ssl_key_passphrase)
+      @ssl_context.cert_store  = load_cert_store
       if @ssl_verify
-        @ssl_context.cert_store  = load_cert_store
         @ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER|OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT
       end
     rescue => e

**Comment by jordansissel** [comment]
For those of you encountering this problem, can you describe how your clients are connecting?

I am able to reproduce this error (`OpenSSL::SSL::SSLError: null cert chain`) when I connect with a TLS client that has no certificate configured, so a null cert makes sense here. The default of `ssl_verify` is `true` and so the tcp input is correctly rejecting a connection without any certificate information. For this specific scenario, if I set `ssl_verify => false` the connection will be accepted without issue. However, I strongly discourage any reduction in security for SSL/TLS, so I recommend always using the default `ssl_verify` (true / enabled).

For this scenario I describe above, I feel Logstash is doing the right thing in both situations (ssl_verify being true and false): when true - the connection is terminated and Logstash logs an error. Should the behavior be different?

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-input-tcp/pull/43 might help with this, though I am not certain (I am scanning through all the open issues for TLS-related failures)

**Comment by nilsnh** [comment]
Also getting the null cert error. But I'm unsure if it has something to do with the way I'm creating my certs or the configuration somehow. My setup works flawlessly when I set `ssl_verify => false` but not if I have it be true. 

I'm using docker logstash:latest, logstash version 2.1.1 and logstash-input-tcp 3.0.0. Here's a link to [my ELK setup](https://github.com/nilsnh/docker-elk-ssl) which is a fork of [docker-elk](https://github.com/deviantony/docker-elk). Logs are sent using [Logstash Logback Encoder version 4.5](https://github.com/logstash/logstash-logback-encoder). 

What I used to create my certs

```bash
openssl req \
  -newkey rsa:2048 -nodes -keyout domain.key \
  -x509 -sha256 -days 365 -out domain.crt
```

And import the cert into a truststore.jks to be used by logback encoder.

```bash
keytool -import -alias selfsigned -file domain.crt -keystore truststore.jks
```

## Logstash error

```ruby
{:timestamp=>"2016-02-03T06:30:37.839000+0000", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: null cert chain>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:262:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.12-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.0/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:206:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:199:in `start_input'"], :level=>:error}
```

## Logback error

```java
08:24:48,773 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[stash] - Log destination 127.0.0.1:5000: connection established.
08:24:48,882 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[stash] - Log destination 127.0.0.1:5000: unable to send event: Remote host closed connection during handshake Reconnecting. javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.doEncode(CompositeJsonEncoder.java:82)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.doEncode(CompositeJsonEncoder.java:30)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:441)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:259)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:320)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:308)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at 	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at 	... 19 common frames omitted
```

Hope this info might help solve this issue. :)

**Comment by jordansissel** [comment]
I don't know much about logback, but null cert, in my experience, means that the client did not present any certificate and the server was requiring one.

**Comment by nilsnh** [comment]
I see what you mean. However the SSL connection seemed to be working fine when I set `ssl_verify => false` and logstash was receiving logs and everything. Now I'm thinking the null cert chain error might be caused by the certificate being self-signed which means that there is no cert chain to follow?

**Comment by nilsnh** [comment]
I'm a little wiser on `ssl_verify => false` thanks to this

> "It means we don't check that the SSL cert name matches the hostname(s)." Source: https://discuss.elastic.co/t/upgraded-logstash-from-1-5-5-to-2-2-0-ssl-heck/42069/3 

Looks like the person in the link also ran into the same `null cert chain` error message.  Either I haven't configured hostname (/CN) correctly in the cert or there might be an issue in my logback configuration. Or it might be because I'm trying to test this whole setup on a single machine. 

Well well. Happy that *I think* I know the meaning of the error message and the implications of setting `ssl_verify => false`.

**Comment by jordansissel** [comment]
"null cert" is a different error than the one you get (in my experience) with a mismatched subject (/CN...) or an untrusted self-signed cert, or an untrusted CA-signed cert that was missing an intermediate certificate.

**Comment by angel-smile** [comment]
Ran into this issue after upgrading logstash from 1.5.6 to 2.2.2. I didn't change any configuration or certificate. It worked without problem for v1.5.6 but started to complain after the upgrade. The certificate used is CA-signed. Don' know why...

**Comment by harbulot** [comment]
I've noticed something else regarding the default CA location.

When the CA is in `/etc/ssl/certs` (with its hash links), and without either `ssl_cacert` or `ssl_extra_chain_certs`, the CA certificate is automatically sent as part of the server certificate chain, so it is indeed picked up by default somehow. Unfortunately, this is not used for client authentication.

A few related points:

* Sending the "root" CA certificate (the last one in the chain) is actually unnecessary, and it may be omitted according to the [TLS specification](https://tools.ietf.org/html/rfc5246#section-7.4.2) (this is only really useful for intermediate CA certificates).

* Relying on building automatically the server certificate chain from all available CA certificates is not necessarily a good idea. There may be multiple valid intermediate certificates in some configurations for the same server certificate, and there's nothing to tell explicitly which chain to choose. Even the `ssl_extra_chain_certs` option used in [`load_cert_store` in `tcp.rb`](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L227) can only *add* new certificates. It doesn't seem to be able to cancel the default behaviour. Multiple valid chains may be an edge case, but it is possible. There doesn't seem to be a way to configure that chain explicitly.

```
  def load_cert_store
    cert_store = OpenSSL::X509::Store.new
    cert_store.set_default_paths
    if File.directory?(@ssl_cacert)
      cert_store.add_path(@ssl_cacert)
    else
      cert_store.add_file(@ssl_cacert)
    end if @ssl_cacert
    @ssl_extra_chain_certs.each do |cert|
      cert_store.add_file(cert)
    end
    cert_store
  end
```

* `ssl_extra_chain_certs` seems to have two purposes: configuring the server certificate chain (despite the problem mentioned above), and building an unordered collection of trust anchors. Effectively, all the certificates are added, but the collection of trust anchors is not ordered, so calling it a "chain" is rather confusing.

* Even if the CA certificates were correctly picked up from the default location for client-certificate authentication, doing so is not necessarily a good idea. A server doesn't necessarily want to advertise *all* the CA certificates it trusts when its system behaves as a client in the `CertificateRequest` TLS message:
  * It may reveal unwanted information to the connecting client (not authenticated at that stage).
  * The list can get quite long, thereby making the `CertificateRequest` message quite big and add extra overhead in the handshake. (This can even cause [critical problems in some cases](http://restlet.tigris.org/ds/viewMessage.do?dsForumId=4447&dsMessageId=2599850).)
  * As a general rule, the server doesn't necessarily want to trust everything its system trusts when it behaves like a client (especially when authentication effectively implies authorisation).

To fix this, I would suggest:

* Re-instating `ssl_cafile`, and make it override whatever default system CA certificates there are when it's used (so as not to trust or advertise all the CA the system trusts when it's a client). This would effectively be the equivalent of [Apache Httpd's `SSLCACertificateFile` Directive](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcacertificatefile):

  > This directive sets the all-in-one file where you can assemble the Certificates of Certification Authorities (CA) whose clients you deal with. These are used for Client Authentication. Such a file is simply the concatenation of the various PEM-encoded Certificate files, in order of preference. This can be used alternatively and/or additionally to SSLCACertificatePath.

* Deprecate `ssl_extra_chain_certs` (at least when effectively used as an unordered collection).

* Allow `ssl_cert` to point to a file that contains the full explicit chain. Again, this would be similar to [Apache Httpd's `SSLCertificateFile`](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatefile)'s behaviour:

  > The files may also include intermediate CA certificates, sorted from leaf to root. This is supported with version 2.4.8 and later, and obsoletes SSLCertificateChainFile. When running with OpenSSL 1.0.2 or later, this allows to configure the intermediate CA chain on a per-certificate basis.

* Alternatively, having a configuration option that points to a file giving the certificate chain that should be used, if needed (effectively similar to Apache Httpd's `SSLCertificateChainFile`).

In any case, there should be a way to separate the CA certificates configuration for the server certificate chain from the configuration of which client certificates to accept.

**Comment by harbulot** [comment]
Talking about SSL/TLS configuration options. It would also be good to be able to configure the protocol versions and the cipher suites. I thought I had seen an issue already open on the topic but I can't find it.

**Comment by ph** [comment]
Yeah, this is a bit problematic I did some work on a similar issue for the beats input, actually certificate chain declared in the same files works on MRI but not on jruby-openssl. see https://github.com/jruby/jruby-openssl/issues/84

`OpenSSL::X509::Store#add_file` accept a certificate chain but the verification isn't correctly done the jruby-openssl implementation. 

Which is in fact a OpenSSL emulation using the java bouncy castle api. This cause problem to know what is actually supporedt since this isn't truly `OpenSSL`'

Agree, `cert_store.set_default_paths` this should be an opt in feature of the plugin.

I will do another pass ASAP since ssl things are fresh to my mind.

**Comment by harbulot** [comment]
Ah, I see, I hadn't realised what it was using under the hood (I'm more familiar with the JSSE in Java).

I've only just had a quick look at the jruby-openssl code:
* It looks like `@cert` can only read one certificate, so we can forget about putting the whole chain there (in a way similar to `SSLCertificateFile` in Apache Httpd). That said, `@extra_chain_cert` should be able to fulfil this purpose (although it's not quite the same as the existing `ssl_extra_chain_certs` option.
* For trusting remote (client) certificate (and by default, which CAs to advertise in `CertificateRequest`), the `ca_path` and `ca_file` settings look like they would work.

Here is a tentative patch that works for me:

```diff
@@ -53,6 +53,8 @@
   # Useful when the CA chain is not necessary in the system store.
   config :ssl_extra_chain_certs, :validate => :array, :default => []
 
+  config :ssl_ca_file, :validate => :path
+
   def initialize(*args)
     super(*args)
 
@@ -213,7 +215,11 @@
       @ssl_context.cert = OpenSSL::X509::Certificate.new(File.read(@ssl_cert))
       @ssl_context.key = OpenSSL::PKey::RSA.new(File.read(@ssl_key),@ssl_key_passphrase)
       if @ssl_verify
-        @ssl_context.cert_store  = load_cert_store
+        @ssl_context.ca_file = @ssl_ca_file
+
+        ca_cert = OpenSSL::X509::Certificate.new(File.read(@ssl_ca_file))
+        @ssl_context.client_ca = [ ca_cert ]
+
         @ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER|OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT
       end
     rescue => e
```

I haven't used `@ssl_context.cert_store  = load_cert_store` (so no defaults at all).

* `@ssl_context.ca_file = @ssl_ca_file` works for two purposes:
  * It adds the CA file to the server certificate chain, which is consistent with [jruby-openssl's `getCertificateChain()` implementation in the `KeyManager`](https://github.com/jruby/jruby-openssl/blob/34aaa64a5b6506f169dff9b39102158cbb69c83e/src/main/java/org/jruby/ext/openssl/SSLContext.java#L963)
  * It's also used as to load the trust anchors.

* `@ssl_context.client_ca = [ ca_cert ]` also seems to work (in my test CA file, there's only one certificate). It does set "`clientCert`" which is used to send the list of certification authorities in the `CertificateRequest` TLS message (`getAcceptedIssuers()` in the `TrustManager`).

  Note that `clientCert` is a variable that is not a client certificate at all. Rather, it implements `client_ca` with the same purpose as [OpenSSL's `SSL_CTX_set_client_CA_list`](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_client_CA_list.html), which sets the list of CAs to request in `CertificateRequest` if there is no CA list configured otherwise. (This is similar to [Apache Httpd's `SSLCADNRequestFile`](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcadnrequestfile).) Looking at the code, it seems this must be set in order to send a non-empty list in the `CertificateRequest` TLS message (it's not populated from the CA file, as it would be with other uses of OpenSSL, perhaps even the non-Java version of Ruby's OpenSSL module.

  That said, it's actually not strictly necessary. Without it, the server will send an empty certification authorities list in its `CertificateRequest` TLS message. This is explicitly allowed in TLS 1.1 and 1.2 (and worked before with many implementations anyway), but the spec doesn't define how verification should happen in this case. In practice here the client certificate is checked against the certificates in `ca_file`. I suppose it would be better to have something that does read through all the concatenated files in the `ca_file` file and passes it in the list.

  (Please also note that the client certificate needs to have purpose attributes compatible with its usage as a client certificate, otherwise the server will reject it even if the rest is configured properly.)

Of course, `@extra_chain_cert` would also need to be set somewhere, so this patch is incomplete.

**Comment by harbulot** [comment]
Coming back to the initial issue (which I've just realised when making the changes above), it does also work with the existing code (despite the problems mentioned in my previous comments), but the client certificate **must** have its usage attributes compatible with SSL client certificate usage.

More on this topic on this page: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Tech_Notes/nss_tech_note3

It works for me with a test cert using:
* X509v3 Key Usage:Digital Signature, Key Encipherment, Data Encipherment
* Netscape Cert Type: SSL Client, S/MIME

(This seems to solve the "null cert chain" issue itself.)

**Comment by vchokshi** [comment]
Hi, I am encountering this same problem with rsyslog. 

On my client I have the full signing chain in PEM format, the server certificate, and authmode set to anon.

My chain only has two certs, the ca and the root (self signed).

On logstash, I have the cert, the key, the chain, and ssl_verify set to false. Once I set it to true and change authmode to x509/name, it fails to authenticate on the client side.

Happy to test anything. I am trying to get other parts of the system working and I'm not too familiar with ruby but it someone can show me how to try that fix recommended above, I could try it!

**Comment by harbulot** [comment]
@vchokshi The problem here is that, when using `ssl_verify => true` on the server, you're actually telling it to use client-certificate authentication (sometimes also referred to as mutual authentication).

As such, you would need to give your client its own certificate (with private key) so that the server can authenticate this client connection. It doesn't look like you've set anything up for that from what you're saying.

There seems to be two problems in what you've tried:

* Using authmode `x509/name` is for the Rsyslog client to verify the server's identity. This has nothing to do with client-certificate authentication. (This is more or less the client's equivalent of `ssl_verify => true`.) This should work even if `ssl_verify` is configured to `false` on the server side. However, the name in the server certificate needs to match the identity you expect from the connection (e.g. its IP address or host name), see [RFC 5425](https://tools.ietf.org/html/rfc5425#section-5.2).

  Here is a sample configuration for Rsyslog (it could vary depending on the version you use):
  ```
$DefaultNetstreamDriverCAFile /path/to/ca.pem
$ActionSendStreamDriver gtls
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode x509/name
```

* Using client-certificate authentication, as required when using `ssl_verify => true` on the Logstash server side. You can achieve this by adding this (this may different in more recent Rsyslog versions):
  ```
$DefaultNetstreamDriverCertFile /.../client-cert.pem
$DefaultNetstreamDriverKeyFile /.../client-key.pem
```

   Of course, for this you would first need to create a client certificate (`client-cert.pem` + `client-key.pem`, for example), with key usage attributes compatible with client side usage. In this case, the *server* now also needs to be configured to be able to verify the client certificate.
  The current Logstash code makes it impossible to do it properly unfortunately (see recent discussions in issue #9).

**Comment by C0rn3j** [comment]
So Logstash verifies things differently than papertrail? As papertrail makes you download this cert bundle https://papertrailapp.com/tools/papertrail-bundle.pem
and uses this conf entry to specify it.
 $DefaultNetstreamDriverCAFile /etc/papertrail-bundle.pem

This config is not needed at all for TLS in Logstash then? All I got to do is disable ssl_verify to not enforce having private certificate for clients?

**Comment by jordansissel** [comment]
@C0rn3j If you are disabling ssl verification, I feel there is little purpose to using TLS at all (disabling verification means you cannot trust nor identify who you are talking to).

**Comment by jordansissel** [comment]
I haven't tried reproducing this, but I wanted to ask -- is this still an ongoing issue?

I think I know what's going on -- based on comments in this issue and things I've learned in the past few months, the `null cert chain` means that Logstash's TLS server requested that a newly-connected client provide a client certificate for identification. If the client has no certificate to offer, then it usually sends a zero-length certificate chain (which java/jruby may be calling a "null cert chain").

This may be a bug in Logstash that the server is requiring a client certificate.

For folks running into this problem, can you attach your Logstash configuration? Specifically, the `input { tcp { ... } }` part.

**Comment by C0rn3j** [comment]
@jordansissel I'm living under the impression that the server communicates via TLS with this config.

	tcp {
    	port => 5000 # syslog port
    	type => syslog
    	ssl_cert  =>  "........./default.crt.pem"
    	ssl_key =>  "........../default.key.pem"
    	ssl_enable  =>  true
    	ssl_verify  =>  false
	}

And clients with this config only communicate to a server via TLS, and they will only communicate if the cert is right?

$DefaultNetstreamDriverCAFile /etc/bla.cert
$ActionSendStreamDriver gtls # use gtls netstream driver
$ActionSendStreamDriverMode 1 # require TLS
$ActionSendStreamDriverAuthMode x509/name # authenticate by hostname
$ActionSendStreamDriverPermittedPeer *.bla.cz

While this does mean that someone could still set up bogus connections and fill my instance with bogus logs, nobody is going to see the actual logs because they're securely communicated via TLS?

**Comment by kmxillo** [comment]
@jordansissel I get the same issue. My logstash config looks like:

`   tcp {
      port               => 40001
      codec              => fluent
      ssl_enable         => true
      ssl_cert           => "cert.pem"
      ssl_key            => "key.pem"
   }`
I am sure the client sends the certificates, therefore the issue must reside on the logstash side. I have been using openssl and fluentd as clients and I get the same error on logstash
