### ISSUE TITLE
failing specs under ng-pipeline

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-tcp#36]
@andrewvc these specs failures seems related to ng-pipeline under master.

```
sing Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

LogStash::Inputs::Tcp
  should read events with json codec (testing 'host' handling) (FAILED - 1)
  should read events with json_lines codec (FAILED - 2)
  should read events with plain codec and ISO-8859-1 charset (FAILED - 3)
  should one message per connection (FAILED - 4)
  should read plain with unicode (FAILED - 5)
  should read events with json codec (FAILED - 6)
  LogStash::Inputs::Tcp new specs style
    behaves like an interruptible input plugin
      #stop
        returns from run
    receive
      should add the host and port to the generated event
      should receive events been generated
      ssl
        should receive events
        when ssl_verify is on
          using an extra chain of certificates
            should receive events
          and using the root CA
            should receive events
          and the verification fails
            should raise an exception when connecting
    register
      should register without errors
  codec (PR #1372)
    switches from json to json_lines
    switches from plain to line

Failures:

  1) LogStash::Inputs::Tcp should read events with json codec (testing 'host' handling)
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  2) LogStash::Inputs::Tcp should read events with json_lines codec
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  3) LogStash::Inputs::Tcp should read events with plain codec and ISO-8859-1 charset
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  4) LogStash::Inputs::Tcp should one message per connection
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  5) LogStash::Inputs::Tcp should read plain with unicode
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

  6) LogStash::Inputs::Tcp should read events with json codec
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/pipeline.rb:258:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:255:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:200:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:169:in `start_workers'

Finished in 10.21 seconds (files took 1.12 seconds to load)
16 examples, 6 failures

Failed examples:

rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:126 # LogStash::Inputs::Tcp should read events with json codec (testing 'host' handling)
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:153 # LogStash::Inputs::Tcp should read events with json_lines codec
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:63 # LogStash::Inputs::Tcp should read events with plain codec and ISO-8859-1 charset
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:190 # LogStash::Inputs::Tcp should one message per connection
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:34 # LogStash::Inputs::Tcp should read plain with unicode
rspec /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-input-tcp/spec/inputs/tcp_spec.rb:91 # LogStash::Inputs::Tcp should read events with json codec

Randomized with seed 16508
```

**Comment by jordansissel** [comment]
I think we can close this since  tests are passing for me.
