### ISSUE TITLE
CA bundle not appended without ssl_verify (OpenSSL::SSL::SSLError: Received fatal alert: unknown_ca)

### ISSUE THREAD

**Issue by hydrapolic** [logstash-plugins/logstash-input-tcp#45]
Using logstash 2.2.0 (tcp-input 3.0.1) with the following configuration I get this error:

```
{:timestamp=>"2016-02-09T08:14:48.851000+0000", :message=>"SSL Error", :exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: unknown_ca>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:272:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.13-java/lib/jopenssl19/openssl/ssl-internal.rb:106:in `accept'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.1/lib/logstash/inputs/tcp.rb:112:in `run_server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.1/lib/logstash/inputs/tcp.rb:84:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.0-java/lib/logstash/pipeline.rb:316:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.0-java/lib/logstash/pipeline.rb:310:in `start_input'"], :level=>:error}
```

```
input {
  tcp {
    port => 1234
    type => syslog

    mode => "server"
    ssl_enable => true
  
    ssl_key => "/etc/ssl/logstash/my.key"
    ssl_cert => "/etc/ssl/logstash/my.pem"
    ssl_extra_chain_certs  => [ "/etc/ssl/logstash/my.ca.pem" ]
    
    ssl_verify => false
  }
}
```

I have syslog-ng servers sending data to the central logstash instance (no client verification). In "my.key" I have the private key, "my.pem" contains only the certificate and "my.ca.pem" contains the CA bundle.

```
# openssl s_client -host localhost -port 1234
CONNECTED(00000003)
depth=0 OU = Domain Control Validated, CN = *.domain.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, CN = *.domain.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.domain.com
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFGzCCBAOgAwIBAgIINlffuBYKp44wDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTUwMjE5MTUyNDQwWhcN
MTYwMjE5MTUyNDQwWjA5MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
ZWQxFDASBgNVBAMMCyouc3lnaWMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAuH0yCRwnntd3Zy7OPMzVk6IiPrRJG/JussuK9/kz6SKTyF6yle6q
NYGjHqSVYKva6Fm3+rKSFkC8S25dz4gtr994rQ23hZYCVvD1FnExR5EsoZOG4XtO
Lv2Ik8yK/fOuMA86fvGFOTlXPw7ZnGTnRfCDDN3+cWLKMbuXMDZsOXtCOt1J8Udc
XVQVmbb43kGgq+1DX0ZAlnShHCq26KVa5nV/Ra6ISQdsNy0H8PMDvILEsdm3ihH6
FvPkyG07gc/rQ3yT8eq4d2/kMJBYoQbsQpPxtCow5eCrb8zwxdyvS8ARPg9xWYgG
b6b+0LraCgZRdpk5Fb4AibodrxF7PjPEvwIDAQABo4IBqTCCAaUwDAYDVR0TAQH/
BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQD
AgWgMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Rp
ZzJzMS04Ny5jcmwwUwYDVR0gBEwwSjBIBgtghkgBhv1tAQcXATA5MDcGCCsGAQUF
BwIBFitodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
MHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRk
eS5jb20vMEAGCCsGAQUFBzAChjRodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHku
Y29tL3JlcG9zaXRvcnkvZ2RpZzIuY3J0MB8GA1UdIwQYMBaAFEDCvSeOzDSDMKIz
1/tss/C0LIDOMCEGA1UdEQQaMBiCCyouc3lnaWMuY29tgglzeWdpYy5jb20wHQYD
VR0OBBYEFAHaiczs/eiTfYM3/tm0QvrEYyqhMA0GCSqGSIb3DQEBCwUAA4IBAQBv
dLoNnToSQApYFw01hr6xUNo4O5x3hYn+lU4F/MV+pTkaPZha2z84+eO8cKKYuOlX
e98hf0ven7Au81c6rGfrxGp8dxwrK/Cvlba/gQ9jIvY7MewidCUeU7wBwC4WANJ0
3brkb8OHWGoH+goSYZPJ9OtBEcFL4/ZId/PiRgkp33lpVBZ7VqgotO0OPFZP9y6D
o+wM8bNjLv36Lxmj/Qu4U2Eab2RvdOCvroy1EXJ8ldYC1af4h2eDv0O13YGVtHTm
swJO2McNYXDH1FHsfbHwhsgB+EQ1ndGLqhsA8PLUv9HmH7W+G8zNCB5E4fOrjMQV
A19c0/6wEXr7qasKL9vI
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/CN=*.domain.com
issuer=/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1835 bytes and written 484 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: 56B9A61749DBF3568251A1C195AB6678B5FF1D6DB25374B41940F6BB5D21C3AD
    Session-ID-ctx: 
    Master-Key: 3398588D12DA11906C04A49366D002121CFDF91C52FE03B760250D9DA4C3545C85E9B19D4C3463A50BA0E52021841ACA
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1455007255
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
```

I suppose this is because the CA bundle is not appended to the cert_store. After this modification it works properly and the whole cert path is sent when connecting to logstash.

```
--- tcp.rb.virgin       2016-02-09 08:07:38.000000000 +0000
+++ tcp.rb      2016-02-09 08:14:57.692775873 +0000
@@ -212,8 +212,8 @@
       @ssl_context = OpenSSL::SSL::SSLContext.new
       @ssl_context.cert = OpenSSL::X509::Certificate.new(File.read(@ssl_cert))
       @ssl_context.key = OpenSSL::PKey::RSA.new(File.read(@ssl_key),@ssl_key_passphrase)
+      @ssl_context.cert_store  = load_cert_store
       if @ssl_verify
-        @ssl_context.cert_store  = load_cert_store
         @ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER|OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT
       end
     rescue => e
```

```
# openssl s_client -host localhost -port 1234
CONNECTED(00000003)
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.domain.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.domain.com
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
 2 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFGzCCBAOgAwIBAgIINlffuBYKp44wDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTUwMjE5MTUyNDQwWhcN
MTYwMjE5MTUyNDQwWjA5MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
ZWQxFDASBgNVBAMMCyouc3lnaWMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAuH0yCRwnntd3Zy7OPMzVk6IiPrRJG/JussuK9/kz6SKTyF6yle6q
NYGjHqSVYKva6Fm3+rKSFkC8S25dz4gtr994rQ23hZYCVvD1FnExR5EsoZOG4XtO
Lv2Ik8yK/fOuMA86fvGFOTlXPw7ZnGTnRfCDDN3+cWLKMbuXMDZsOXtCOt1J8Udc
XVQVmbb43kGgq+1DX0ZAlnShHCq26KVa5nV/Ra6ISQdsNy0H8PMDvILEsdm3ihH6
FvPkyG07gc/rQ3yT8eq4d2/kMJBYoQbsQpPxtCow5eCrb8zwxdyvS8ARPg9xWYgG
b6b+0LraCgZRdpk5Fb4AibodrxF7PjPEvwIDAQABo4IBqTCCAaUwDAYDVR0TAQH/
BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQD
AgWgMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Rp
ZzJzMS04Ny5jcmwwUwYDVR0gBEwwSjBIBgtghkgBhv1tAQcXATA5MDcGCCsGAQUF
BwIBFitodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
MHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRk
eS5jb20vMEAGCCsGAQUFBzAChjRodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHku
Y29tL3JlcG9zaXRvcnkvZ2RpZzIuY3J0MB8GA1UdIwQYMBaAFEDCvSeOzDSDMKIz
1/tss/C0LIDOMCEGA1UdEQQaMBiCCyouc3lnaWMuY29tgglzeWdpYy5jb20wHQYD
VR0OBBYEFAHaiczs/eiTfYM3/tm0QvrEYyqhMA0GCSqGSIb3DQEBCwUAA4IBAQBv
dLoNnToSQApYFw01hr6xUNo4O5x3hYn+lU4F/MV+pTkaPZha2z84+eO8cKKYuOlX
e98hf0ven7Au81c6rGfrxGp8dxwrK/Cvlba/gQ9jIvY7MewidCUeU7wBwC4WANJ0
3brkb8OHWGoH+goSYZPJ9OtBEcFL4/ZId/PiRgkp33lpVBZ7VqgotO0OPFZP9y6D
o+wM8bNjLv36Lxmj/Qu4U2Eab2RvdOCvroy1EXJ8ldYC1af4h2eDv0O13YGVtHTm
swJO2McNYXDH1FHsfbHwhsgB+EQ1ndGLqhsA8PLUv9HmH7W+G8zNCB5E4fOrjMQV
A19c0/6wEXr7qasKL9vI
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/CN=*.domain.com
issuer=/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4046 bytes and written 484 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: 56B9A6971824FC9AE9182274BD6432E9297776E30542DD5DE2CCCAD2F4069ACA
    Session-ID-ctx: 
    Master-Key: D0A5F0DA22299FF523928C40DD56C3F335444E3391EF754967F741B6CF2FDD0EA45007FADA9EDDC5F54C6CBD0FE738CD
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1455007383
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
--
```

**Comment by hydrapolic** [comment]
Still a problem with the latest logstash release.

**Comment by cameronkerrnz** [comment]
Still a problem in logstash 6.3.0. Looks like I'll have to patch it manually to add in the functionality I require to migrate away from our existing nxlog deployment.

**Comment by hydrapolic** [comment]
Each time I update logstash,the change has to be done,it's a bit frustrating after that amount of time :)

**Comment by cameronkerrnz** [comment]
Also worth noting that the current behaviour of ssl_verify of this repo (at least up to 5.0.9 when I wrote this) with regard to using the default trust stores is justifiably a security issue.
