### ISSUE TITLE
Test failling when run under logstash `rake test:plugins`

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-tcp#46]
Randomized with seed 30061

```
 1) LogStash::Inputs::Tcp LogStash::Inputs::Tcp new specs style #receive when ssl_enable is true with a poorly-behaving client connection was healthy but now has garbage or corruption should not negatively impact the plugin
     Failure/Error: sslsocket.connect
     OpenSSL::SSL::SSLError:
       Socket closed
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.2/spec/inputs/tcp_spec.rb:344:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
```

**Comment by kares** [comment]
seems to be resolved by now
