### ISSUE TITLE
Using a certificate with a passphrase doesnt currently work.

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-tcp#48]
I have generate a self signed certificate that use a passphrase with the following command:
```
openssl req -x509  -batch -newkey rsa:2048 -keyout server.key -out server.crt -subj /CN=localhost
```
With the `abc123` passphrase I was expecting it to work, but wwhen I launch logstash with the following settings:

```
input {
  tcp {
    port => 5555
    ssl_enable => true
    ssl_cert => "/Users/ph/es/logstash-config/input_tcp/server.crt"
    ssl_key =>  "/Users/ph/es/logstash-config/input_tcp/server.key"
    ssl_key_passphrase => "abc123"
  }
}
output {
  stdout  {
    codec => rubydebug
  }
}
```
I see the following output in the 
```
Settings: Default pipeline workers: 4
Could not inititalize SSL context {:exception=>#<OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key:>, :backtrace=>["org/jruby/ext/openssl/PKeyRSA.java:277:in `initialize'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.2/lib/logstash/inputs/tcp.rb:214:in `ssl_context'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.2/lib/logstash/inputs/tcp.rb:250:in `new_server_socket'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-3.0.2/lib/logstash/inputs/tcp.rb:79:in `register'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:319:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:318:in `start_inputs'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:169:in `start_workers'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:123:in `run'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/agent.rb:211:in `execute'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:90:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:95:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/Users/ph/es/stable/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:error}
The error reported is:
  Neither PUB key nor PRIV key:
```

I use the following crt/key for the configuration. https://gist.github.com/9e22fc86b9fa10727635

**Comment by ph** [comment]
I think the issue isnt with the code but with the way the certificate was generated, checking this.

**Comment by ph** [comment]
Openssl's s_server ask for the passphrase and correctly start?
```
~/e/l/input_tcp ❯❯❯ openssl s_server -accept 5555 -cert ./server.crt -key ./server.key                                                                      ⏎
Enter pass phrase for ./server.key:
Using default temp DH parameters
Using default temp ECDH parameters
ACCEPT
```

**Comment by ph** [comment]
The problem should be located there https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L214, this option is a `password` type and we need to explicitely call `value` on it, If we don't do this we will try to decrypt the key with `<Password>` and it will obviously fails.

I think I also have this bug in the beats input, creating an issue for it too.

**Comment by CraigFoote** [comment]
Thanks! In what version of logstash should I expect to find this fix?

**Comment by ph** [comment]
@CraigFoote it will be bundled in logstash 2.3, but you can update the plugin to use it.

`bin/plugin update logstash-input-tcp`

It should install version 3.0.4

**Comment by CraigFoote** [comment]
Thanks again @ph
