### ISSUE TITLE
Job failling on JRuby 9K

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-tcp#69]
https://travis-ci.org/logstash-plugins/logstash-input-tcp/jobs/236451179
```
tart_workers'
  8) LogStash::Inputs::Tcp codec (PR #1372) switches from json to json_lines
     Failure/Error: (output_func(event) || []).each do |output|
     
     NoMethodError:
       undefined method `each' for #<Queue:0x5807ea46>
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:400:in `block in output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `block in each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:394:in `output_batch'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:352:in `worker_loop'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-core-5.4.0-java/lib/logstash/pipeline.rb:317:in `block in start_workers'
Finished in 5.16 seconds (files took 3.39 seconds to load)
14 examples, 8 failures
Failed examples:
rspec ./spec/inputs/tcp_spec.r

**Comment by kares** [comment]
defunct by now, closing ...
